name: rome
channels:
  - defaults
  - conda-forge
  - plotly
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - pip=23.3.1
  - python=3.11.8
  - conda-lock=1.4.0
  - hydra-core=1.3.2
  - pytorch=2.1.2
  - pytorch-lightning=2.2.1
  - pytorch-cuda=11.8
  - torchvision=0.16.1
  - transformers=4.37.2
  - rich=13.3.5
  - scikit-image=0.22.0
  - plotly=5.19.0
  - folium=0.17.0
  - seaborn=0.12.2
  - tqdm=4.65.0
  - python-dotenv=0.21.0
  - tabulate=0.9.0
  - streamlit=1.32.0
  - scipy=1.11.4
  - osmnx=1.9.1
  - geopy=2.4.1
  - pyproj=3.6.1
  - openpyxl=3.0.10
  - shapely=2.0.3
  - numpy=1.26.4
  - altair=5.0.1
  - pip:
      - aim==3.18.1
