_target_: src.utils.WarmupStableDecayLR

warmup_epochs: 5
decay_epochs: 5
max_epochs: ${trainer.max_epochs}
warmup_start_lr: 0
stable_lr: 2e-4
eta_min: 0.0
last_epoch: -1
interval: 'epoch' # 'step' or 'epoch'
