_target_: src.networks.ViTPlusPlusUPerNet

num_classes: 1
image_size: 224

mlp_input_dim: 6

v_num_channels: 3
v_patch_size: 16
v_hidden_size: 768
v_num_hidden_layers: 12
v_num_attention_heads: 12
res_hidden_states: null
use_upernet: True
up_pool_scales: [ 1, 2, 4, 7 ]
neck_input_dim: null
neck_scales: null
neck_size: null
pre_out_channels: null
pretrained: openai/clip-vit-base-patch16

model_type: clip