_target_: src.networks.ViTPlusPlusUPerNet

num_classes: 1
image_size: 224

mlp_input_dim: 6
min_mlp_tokens: 3

v_num_channels: 3
v_patch_size: 14
v_hidden_size: 1024
v_num_hidden_layers: 24
v_num_attention_heads: 16
mixer_out: null
res_hidden_states: null  # [ 1, 5, 9, 13 ]
use_upernet: False
up_pool_scales: [ 1, 2, 4, 7 ]
neck_input_dim: null
neck_scales: null # [ 16, 8, 2, 1 ]
neck_size: null # [ 96, 192, 384, 768 ]
pre_out_channels: 3
pretrained: facebook/dinov2-large

model_type: dino_v2