model_checkpoint_2:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_2_mse_meters # name of the logged metric which determines when model is improving
  mode: min # can be "max" or "min"
  save_top_k: 1 # save k best models (determined by above metric) | if -1, all models are saved.
  save_last: False # additionally, always save model from last epoch
  verbose: False
  dirpath: checkpoints/easy/
  filename: epoch_{epoch:04d}
  auto_insert_metric_name: False