# @package _global_
name: evaluation
seed: 0
print_config: True
ignore_warnings: True


prediction_path: ${oc.env:PREDICTIONS_PATH}/test/2025-02-06_09-31-33.881257_o/  # only needed for prediction mode
split: test
is_rome: True

error_tolerance: [ 1, 5, 10, 20, 30, 40, 50 ]
size_bins: [ 200, 400, 600, 800, 1000, 1200, 1400, 1600 ]

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True