# @package _global_
name: oslo_generate_data
seed: 0
print_config: True
ignore_warnings: False

mat_file: ${oc.env:OSLO_MAT_FILE}
cell_file: ${oc.env:OSLO_CELL_FILE}
sionna_csv: null
out_dir: ${oc.env:OSLO_OUT_DIR}
mat_keyword: dataSet
buildings_gpkg_path: ${oc.env:CACHE_DIR}/buildings.gpkg
roads_gpkg_path: ${oc.env:CACHE_DIR}/roads.gpkg
random_point_scale_factor: 0.9
nsew: [ 59.94, 59.90, 10.71, 10.77 ]
workers: null

num_points: 1500000
sample_per_ue: null

grid_size: null
grid_subspace_start: null
grid_subspace_end: null

random_size_mean: 300
random_size_std: 0
random_size_min: 100
random_size_max: 800

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True