# @package _global_
name: oslo_create_info_json
seed: 0
print_config: True
ignore_warnings: True

main_path: ${oc.env:OSLO_OUT_DIR}
dataset_type: dataSet

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True