# @package _global_
name: oslo_train_test_split
seed: 0
print_config: True
ignore_warnings: True

out_dir: ${oc.env:OSLO_OUT_DIR}

train_only: True
hard_test_campaign: "4"
hard_train: 0.0
hard_test: 1.0
hard_val_nsew: [ 59.9235, 59.9225, 10.742, 10.740 ]
medium_train: 0.95
medium_test: 0.5
easy_train: 0.99
easy_test: 0.5

hard_margin_meters: 601

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True