# @package _global_
name: rome_train_test_split
seed: 0
print_config: True
ignore_warnings: True

out_dir: ${oc.env:ROME_OUT_DIR}

train_only: False
dataset_type: dataSet
hard_test_campaign: "5"
hard_train: 0
hard_test: 1.0
hard_val_nsew: [ 41.85, 41.84, 12.49, 12.45 ]
medium_train: 0.9
medium_test: 0.5
easy_train: 0.99
easy_test: 0.5

hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: True