_target_: src.datamodules.RomeDatamodule

batch_size: 10
num_workers: 15

dataset_main_paths:
  - ${oc.env:ROME_OUT_DIR}
  - ${oc.env:ROME_SIONNA_OUT_DIR_C}
train_dataset_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/train.json
hard_val_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/hard_val.json
hard_test_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/hard_test.json
medium_val_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/medium_val.json
medium_test_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/medium_test.json
easy_val_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/easy_val.json
easy_test_json_paths:
  - ${oc.env:ROME_SPLITS_PATH}/easy_test.json

min_num_bs: 3
max_num_bs: 9999
hard_campaign: "5"
hard_train_ratio: 0.0
dataset_types: [ dataSet, dataSet ]
map_size: 224
features:
  - RSSI
  - NSINR
  - NRSRP
  - NRSRQ
  - bs_power_dbm
feature_means:
  RSSI: -64
  NSINR: -5.0
  NRSRP: -83.0
  NRSRQ: -19.0
  bs_power_dbm: 0.0
feature_vars:
  RSSI: 57.0
  NSINR: 94.0
  NRSRP: 114.0
  NRSRQ: 41.0
  bs_power_dbm: 1.0
bs_power_dropout_rate: 0.0
output_gaussian_sigma: 3.0
decimal_places: 10
eps_image: 3
for_viz: False
map_channels: buildings # buildings, roads, both
crops_per_epoch: 10